int numberOfSandwhiches;
int numberOfToppings;
//Console.WriteLine(numberOfSandwhiches);
const double COST_OF_SANDWHICH = 4.75;
const double COST_OF_TOPPING = 0.55;
const double DISCOUNT_AMOUNT = .10;
Console.WriteLine("Number of Sandwhiches");
numberOfSandwhiches = int.Parse(Console.ReadLine());
Console.WriteLine("Number of Toppings");
numberOfToppings = int.Parse(Console.ReadLine());
Console.WriteLine("Tip Amount");
double tipNumber = double.Parse(Console.ReadLine());
double totalSandwhichCost = COST_OF_SANDWHICH * numberOfSandwhiches;
double totalToppingCost = COST_OF_TOPPING * numberOfToppings;
double baseCost = totalSandwhichCost + totalToppingCost;
double orderCost = tipNumber + baseCost * (1-DISCOUNT_AMOUNT);
Console.WriteLine(" Total Cost " + orderCost);